import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthSessionWatcher from './components/AuthSessionWatcher'
import ProfileAvatar from './components/ProfileAvatar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthSessionWatcher>
          <div className="absolute top-4 right-4 z-50">
            <ProfileAvatar />
          </div>
          {children}
        </AuthSessionWatcher>
      </body>
    </html>
  );
}
